# Generated by Django 4.2.16 on 2026-07-02 09:52

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mixins.mixing
import validation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('help_time', models.CharField(default='24/7 Support', max_length=150)),
                ('image', models.ImageField(upload_to='allows_payments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), validation.validators.validate_image_size])),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '10. Allow Payments',
                'db_table': 'store_allow_payments',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='brands/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), validation.validators.validate_image_size])),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '02. Brands',
                'db_table': 'store_brands',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='categories/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), validation.validators.validate_image_size])),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '01. Categories',
                'db_table': 'store_categories',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': '03. Colors',
                'db_table': 'store_colors',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ColorTagMixin),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), validation.validators.validate_image_size])),
            ],
            options={
                'verbose_name_plural': '06. Galleries',
                'db_table': 'store_galleries',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('variants_type', models.CharField(choices=[('none', 'None'), ('color', 'Color'), ('size', 'Size'), ('color_size', 'Color Size')], default='none', max_length=20)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000)])),
                ('sold', models.PositiveIntegerField(default=0)),
                ('visited', models.PositiveIntegerField(default=0)),
                ('prev_des', models.TextField(blank=True, null=True)),
                ('add_des', models.TextField(blank=True, null=True)),
                ('short_des', models.TextField(blank=True, null=True)),
                ('long_des', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_deadline', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': '05. Products',
                'db_table': 'store_products',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=500)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name_plural': '09. Reviews',
                'db_table': 'store_reviews',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': '04. Sizes',
                'db_table': 'store_sizes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('variant_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size')),
            ],
            options={
                'verbose_name_plural': '07. Variant Options',
                'db_table': 'store_variant_options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slider_type', models.CharField(choices=[('none', 'None'), ('slider', 'Slider'), ('add', 'Add'), ('feature', 'Feature'), ('promotion', 'Promotion')], max_length=20)),
                ('headline', models.CharField(blank=True, max_length=150, null=True)),
                ('paragraph', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(upload_to='sliders/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), validation.validators.validate_image_size])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': '08. Sliders',
                'db_table': 'store_sliders',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['title'], name='store_sizes_title_50c26d_idx'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['code'], name='store_sizes_code_dfd52d_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='store.product'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['title'], name='store_color_title_a81357_idx'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['code'], name='store_color_code_47d5a6_idx'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['title'], name='store_brand_title_d42766_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['slug'], name='store_brand_slug_6b9e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='allowpayment',
            index=models.Index(fields=['is_featured'], name='store_allow_is_feat_ad0eb5_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['product'], name='store_varia_product_aa4a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['sku'], name='store_varia_sku_5f15c4_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['variant_price'], name='store_varia_variant_79286b_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['stock'], name='store_varia_stock_23625d_idx'),
        ),
        migrations.AddIndex(
            model_name='slider',
            index=models.Index(fields=['product'], name='store_slide_product_94becc_idx'),
        ),
        migrations.AddIndex(
            model_name='slider',
            index=models.Index(fields=['slider_type'], name='store_slide_slider__29befa_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='store_revie_product_8e0ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='store_revie_user_id_d67233_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title'], name='store_produ_title_c2c364_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='store_produ_slug_981c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['old_price'], name='store_produ_old_pri_f130dc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sale_price'], name='store_produ_sale_pr_668917_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['discount'], name='store_produ_discoun_b63663_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock'], name='store_produ_stock_ac4eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sold'], name='store_produ_sold_96be26_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['visited'], name='store_produ_visited_b24e40_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_deadline'], name='store_produ_is_dead_627cc5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured'], name='store_produ_is_feat_eca39f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='store_produ_status_18ff48_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['product'], name='store_galle_product_2d52ee_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='store_categ_title_bd4696_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='store_categ_slug_7ee8fd_idx'),
        ),
    ]
