# Generated by Django 4.2.16 on 2026-06-01 15:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mixins.mixing
import validation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('help_time', models.CharField(default='24/7 Support', max_length=150)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='allows_payments/%Y/%m/%d/', validators=[validation.validators.validate_image_size])),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '10. Allow Payment',
                'verbose_name_plural': '10. Allow Payments',
                'db_table': 'store_allow_payments',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='keyword')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='brands/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), validation.validators.validate_image_size], verbose_name='image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is_featured')),
            ],
            options={
                'verbose_name': '02. Brand',
                'verbose_name_plural': '02. Brands',
                'db_table': 'store_brands',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='keyword')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='categories/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), validation.validators.validate_image_size], verbose_name='image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is_featured')),
            ],
            options={
                'verbose_name': '01. Category',
                'verbose_name_plural': '01. Categories',
                'db_table': 'store_categories',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': '03. Product Color',
                'verbose_name_plural': '03. Product Colors',
                'db_table': 'store_colors',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ColorTagMixin),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('image', models.ImageField(upload_to='products/gallery/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), validation.validators.validate_image_size], verbose_name='image')),
            ],
            options={
                'verbose_name': '06. Gallery',
                'verbose_name_plural': '06. Galleries',
                'db_table': 'store_galleries',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('keyword', models.CharField(blank=True, max_length=255, null=True, verbose_name='keyword')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('variants_type', models.CharField(choices=[('none', 'None'), ('color', 'Color'), ('size', 'Size'), ('color_size', 'Color Size')], default='none', max_length=20)),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('tag', models.CharField(blank=True, max_length=150, null=True, verbose_name='tag')),
                ('old_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='old price')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='sale price')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='discount')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='stock')),
                ('sold', models.PositiveIntegerField(default=0, verbose_name='sold')),
                ('visited', models.PositiveIntegerField(default=0, verbose_name='visited')),
                ('prev_des', models.TextField(blank=True, null=True, verbose_name='prev_des')),
                ('add_des', models.TextField(blank=True, null=True, verbose_name='add_des')),
                ('short_des', models.TextField(blank=True, null=True, verbose_name='short_des')),
                ('long_des', models.TextField(blank=True, null=True, verbose_name='long_des')),
                ('deadline', models.DateTimeField(blank=True, null=True, verbose_name='deadline')),
                ('is_deadline', models.BooleanField(default=False, verbose_name='is_deadline')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is_featured')),
            ],
            options={
                'verbose_name': '05. Product',
                'verbose_name_plural': '05. Products',
                'db_table': 'store_products',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('subject', models.CharField(max_length=50)),
                ('comment', models.TextField(max_length=500)),
                ('rating', models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'verbose_name': '09. Review',
                'verbose_name_plural': '09. Reviews',
                'db_table': 'store_reviews',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='title')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='code')),
            ],
            options={
                'verbose_name': '04. Product Size',
                'verbose_name_plural': '04. Product Sizes',
                'db_table': 'store_sizes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VariantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('image_id', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('variant_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='store.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.size')),
            ],
            options={
                'verbose_name': '07. Variant Option',
                'verbose_name_plural': '07. Variant Options',
                'db_table': 'store_variant_options',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('slider_type', models.CharField(choices=[('none', 'None'), ('slider', 'Slider'), ('add', 'Add'), ('feature', 'Feature'), ('promotion', 'Promotion')], default='none', max_length=10)),
                ('headline', models.CharField(blank=True, max_length=150, null=True)),
                ('paragraph', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(default='defaults/default.jpg', upload_to='sliders/%Y/%m/%d/', validators=[validation.validators.validate_image_size])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': '08. Slider',
                'verbose_name_plural': '08. Sliders',
                'db_table': 'store_sliders',
                'ordering': ['id'],
            },
            bases=(models.Model, mixins.mixing.ImageTagMixin),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['title', 'code'], name='store_sizes_title_2f5ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='size',
            index=models.Index(fields=['status', 'created_at'], name='store_sizes_status_a7240e_idx'),
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.category'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='store.product'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['title', 'code'], name='store_color_title_dcb9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='color',
            index=models.Index(fields=['status', 'created_at'], name='store_color_status_2fceec_idx'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='store.category'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['title', 'slug'], name='store_brand_title_7b20b3_idx'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_featured', 'status', 'created_at'], name='store_brand_is_feat_d9baf9_idx'),
        ),
        migrations.AddIndex(
            model_name='allowpayment',
            index=models.Index(fields=['title'], name='store_allow_title_c156a3_idx'),
        ),
        migrations.AddIndex(
            model_name='allowpayment',
            index=models.Index(fields=['is_featured', 'status', 'created_at'], name='store_allow_is_feat_a3679c_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['product'], name='store_varia_product_aa4a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['color'], name='store_varia_color_i_2915c0_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['size'], name='store_varia_size_id_a46d19_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['sku', 'variant_price', 'stock'], name='store_varia_sku_fc1bec_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['status'], name='store_varia_status_ecd4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='variantoption',
            index=models.Index(fields=['created_at'], name='store_varia_created_f0066b_idx'),
        ),
        migrations.AddIndex(
            model_name='slider',
            index=models.Index(fields=['product'], name='store_slide_product_94becc_idx'),
        ),
        migrations.AddIndex(
            model_name='slider',
            index=models.Index(fields=['slider_type'], name='store_slide_slider__29befa_idx'),
        ),
        migrations.AddIndex(
            model_name='slider',
            index=models.Index(fields=['created_at'], name='store_slide_created_62b459_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='store_revie_product_8e0ddc_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='store_revie_user_id_d67233_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='store_revie_rating_c77f10_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['created_at'], name='store_revie_created_1b3796_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand', 'variants_type'], name='store_produ_categor_2d12ac_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['title', 'slug', 'tag', 'old_price', 'sale_price', 'stock'], name='store_produ_title_bd732d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sold', 'visited', 'deadline', 'is_deadline'], name='store_produ_sold_939f75_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'status', 'created_at'], name='store_produ_is_feat_aed6d6_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['product'], name='store_galle_product_2d52ee_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['status'], name='store_galle_status_1847db_idx'),
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['created_at'], name='store_galle_created_e951e5_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'title', 'slug'], name='store_categ_parent__07e661_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured', 'status', 'created_at'], name='store_categ_is_feat_f528fd_idx'),
        ),
    ]
